"""
Output Manager Tool - Manage output files generated by AI-ONE tools.

This tool provides operations for listing, cleaning up, and organizing
files in the universal outputs directory.
"""

from typing import Dict, Any, Optional, Literal
from pydantic import BaseModel, Field
import time

from one_think.tools.base import Tool, ToolResponse
from one_think.utils.output_manager import output_manager


class OutputManagerTool(Tool):
    """Tool for managing AI-ONE output files."""
    
    name = "output_manager"
    description = "Manage output files generated by AI-ONE tools"
    version = "1.0.0"
    
    # Pydantic schemas for validation
    class Input(BaseModel):
        """Input parameters for output management."""
        operation: Literal["list", "cleanup", "stats"] = Field(description="Operation type")
        tool_filter: Optional[str] = Field(default=None, description="Filter by tool name (for list operation)")
        hours: Optional[int] = Field(default=24, ge=1, le=168, description="Hours for cleanup (1-168, default: 24)")
        
    class Output(BaseModel):
        """Output format for output management."""
        operation: str = Field(description="Operation performed")
        success: bool = Field(description="Whether operation succeeded")
        files: Optional[list] = Field(description="List of files (for list operation)")
        count: Optional[int] = Field(description="Number of files")
        total_size: Optional[int] = Field(description="Total size in bytes")
        removed: Optional[int] = Field(description="Number of files removed (for cleanup)")
        message: Optional[str] = Field(description="Status message")
        
    def execute_json(self, params: Dict[str, Any], request_id: Optional[str] = None) -> ToolResponse:
        """Execute output management operation."""
        start_time = time.time()
        
        try:
            # Validate input parameters
            validated_input = self.validate_input(params)
            
            # Execute operation
            if validated_input.operation == "list":
                result = self._list_files(validated_input)
            elif validated_input.operation == "cleanup":
                result = self._cleanup_files(validated_input)  
            elif validated_input.operation == "stats":
                result = self._get_stats(validated_input)
            else:
                return ToolResponse(
                    status="error",
                    tool=self.name,
                    request_id=request_id,
                    error={"type": "invalid_operation", "message": f"Unknown operation: {validated_input.operation}"},
                    execution_time_ms=(time.time() - start_time) * 1000
                )
            
            # Validate output
            validated_output = self.validate_output(result)
            
            return ToolResponse(
                status="success",
                tool=self.name,
                request_id=request_id,
                result=validated_output.model_dump(),
                execution_time_ms=(time.time() - start_time) * 1000
            )
            
        except Exception as e:
            return ToolResponse(
                status="error",
                tool=self.name,
                request_id=request_id,
                error={"type": "execution_error", "message": str(e)},
                execution_time_ms=(time.time() - start_time) * 1000
            )
    
    def _list_files(self, input_data) -> Dict[str, Any]:
        """List output files with optional tool filter."""
        file_info = output_manager.list_outputs(input_data.tool_filter)
        
        return {
            "operation": "list",
            "success": True,
            "files": file_info["files"],
            "count": file_info["count"],
            "total_size": file_info["total_size"],
            "removed": None,
            "message": f"Found {file_info['count']} files" + 
                      (f" for tool '{input_data.tool_filter}'" if input_data.tool_filter else "")
        }
    
    def _cleanup_files(self, input_data) -> Dict[str, Any]:
        """Clean up old temporary files."""
        cleanup_info = output_manager.cleanup_temp_files(input_data.hours)
        
        return {
            "operation": "cleanup", 
            "success": True,
            "files": cleanup_info["files"],
            "count": None,
            "total_size": cleanup_info["total_size"],
            "removed": cleanup_info["removed"],
            "message": f"Removed {cleanup_info['removed']} temporary files "
                      f"({cleanup_info['total_size']} bytes) older than {input_data.hours}h"
        }
    
    def _get_stats(self, input_data) -> Dict[str, Any]:
        """Get statistics about output directory."""
        all_files = output_manager.list_outputs()
        temp_files = output_manager.list_outputs()  # Could filter temp files
        
        # Group by tool
        tool_stats = {}
        for file_info in all_files["files"]:
            tool_name = file_info["name"].split("_")[0]
            if tool_name not in tool_stats:
                tool_stats[tool_name] = {"count": 0, "size": 0}
            tool_stats[tool_name]["count"] += 1
            tool_stats[tool_name]["size"] += file_info["size"]
        
        return {
            "operation": "stats",
            "success": True,
            "files": list(tool_stats.keys()),
            "count": all_files["count"],
            "total_size": all_files["total_size"],
            "removed": None,
            "message": f"Total: {all_files['count']} files, {all_files['total_size']} bytes. "
                      f"Tools: {', '.join(tool_stats.keys())}"
        }
    
    def get_help(self) -> str:
        """Return comprehensive help text."""
        return """OUTPUT MANAGER TOOL

Manage output files generated by AI-ONE tools with listing, cleanup, and statistics.

OPERATIONS:

1. list - List output files
   Parameters:
   - tool_filter (optional): Filter by tool name (e.g., "tts", "whisper")
   
   Example: {"operation": "list", "tool_filter": "tts"}

2. cleanup - Clean up old temporary files  
   Parameters:
   - hours (optional): Remove temp files older than this (1-168, default: 24)
   
   Example: {"operation": "cleanup", "hours": 48}

3. stats - Get output directory statistics
   Parameters: None
   
   Example: {"operation": "stats"}

OUTPUTS DIRECTORY STRUCTURE:
- outputs/audio/ - TTS and audio files
- outputs/temp/ - Temporary files (auto-cleanup)
- outputs/ - General tool outputs

The tool automatically organizes files by type and provides cleanup for temporary files.
Use 'list' to see all generated files, 'cleanup' to remove old temp files, and 'stats' for overview.
"""