"""
Universal Output Directory Management for AI-ONE Tools.

This module provides a centralized system for managing output files
generated by AI-ONE tools, with consistent naming and organization.
"""

import os
import time
import uuid
from pathlib import Path
from typing import Optional, Dict, Any


class OutputManager:
    """
    Centralized manager for tool output files.
    
    Features:
    - Consistent naming conventions
    - Auto-directory creation
    - File type organization
    - Cleanup utilities
    """
    
    def __init__(self, base_dir: str = "outputs"):
        """
        Initialize OutputManager.
        
        Args:
            base_dir: Base directory for all outputs (default: 'outputs')
        """
        self.base_dir = Path(base_dir)
        self.base_dir.mkdir(exist_ok=True)
        
    def get_output_path(
        self, 
        tool_name: str, 
        file_type: str, 
        custom_name: Optional[str] = None,
        subdirectory: Optional[str] = None
    ) -> Path:
        """
        Generate standardized output path for tool files.
        
        Args:
            tool_name: Name of the tool generating the file
            file_type: File extension (e.g., 'wav', 'txt', 'json')
            custom_name: Custom filename (without extension)
            subdirectory: Optional subdirectory (e.g., 'audio', 'images')
            
        Returns:
            Path object for the output file
            
        Examples:
            get_output_path('tts', 'wav') → outputs/tts_1234567890.wav
            get_output_path('whisper', 'txt', 'transcript') → outputs/whisper_transcript.txt
            get_output_path('python', 'py', 'script', 'temp') → outputs/temp/python_script.py
        """
        # Create subdirectory if specified
        if subdirectory:
            output_dir = self.base_dir / subdirectory
            output_dir.mkdir(exist_ok=True)
        else:
            output_dir = self.base_dir
        
        # Generate filename
        if custom_name:
            filename = f"{tool_name}_{custom_name}.{file_type}"
        else:
            timestamp = int(time.time() * 1000)
            filename = f"{tool_name}_{timestamp}.{file_type}"
            
        return output_dir / filename
    
    def get_temp_path(
        self, 
        tool_name: str, 
        file_type: str,
        session_id: Optional[str] = None
    ) -> Path:
        """
        Generate temporary file path with automatic cleanup info.
        
        Args:
            tool_name: Name of the tool
            file_type: File extension
            session_id: Optional session ID for grouping
            
        Returns:
            Path for temporary file in outputs/temp/
        """
        temp_dir = self.base_dir / "temp"
        temp_dir.mkdir(exist_ok=True)
        
        # Include session in filename for easier cleanup
        if session_id:
            unique_id = f"{session_id[:8]}_{uuid.uuid4().hex[:8]}"
        else:
            unique_id = uuid.uuid4().hex[:12]
            
        filename = f"{tool_name}_temp_{unique_id}.{file_type}"
        return temp_dir / filename
    
    def cleanup_temp_files(self, older_than_hours: int = 24) -> Dict[str, Any]:
        """
        Clean up old temporary files.
        
        Args:
            older_than_hours: Remove files older than this (default: 24h)
            
        Returns:
            Dictionary with cleanup stats
        """
        temp_dir = self.base_dir / "temp"
        if not temp_dir.exists():
            return {"removed": 0, "total_size": 0, "files": []}
        
        import time
        cutoff_time = time.time() - (older_than_hours * 3600)
        
        removed_files = []
        total_size = 0
        
        for file_path in temp_dir.glob("*"):
            if file_path.is_file():
                file_mtime = file_path.stat().st_mtime
                if file_mtime < cutoff_time:
                    file_size = file_path.stat().st_size
                    total_size += file_size
                    removed_files.append(str(file_path.name))
                    file_path.unlink()
        
        return {
            "removed": len(removed_files),
            "total_size": total_size,
            "files": removed_files
        }
    
    def list_outputs(self, tool_name: Optional[str] = None) -> Dict[str, Any]:
        """
        List all output files, optionally filtered by tool.
        
        Args:
            tool_name: Optional tool name filter
            
        Returns:
            Dictionary with file listing and stats
        """
        files = []
        total_size = 0
        
        for file_path in self.base_dir.rglob("*"):
            if file_path.is_file():
                if tool_name is None or file_path.name.startswith(f"{tool_name}_"):
                    file_size = file_path.stat().st_size
                    files.append({
                        "name": file_path.name,
                        "path": str(file_path),
                        "size": file_size,
                        "modified": file_path.stat().st_mtime
                    })
                    total_size += file_size
        
        return {
            "files": sorted(files, key=lambda f: f["modified"], reverse=True),
            "count": len(files),
            "total_size": total_size
        }


# Global instance for easy import
output_manager = OutputManager()


def get_output_path(tool_name: str, file_type: str, custom_name: Optional[str] = None, subdirectory: Optional[str] = None) -> Path:
    """Convenience function for getting output paths."""
    return output_manager.get_output_path(tool_name, file_type, custom_name, subdirectory)


def get_temp_path(tool_name: str, file_type: str, session_id: Optional[str] = None) -> Path:
    """Convenience function for getting temporary paths.""" 
    return output_manager.get_temp_path(tool_name, file_type, session_id)